<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("countries", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit countries
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "countries/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldCountryName" class="col-sm-2 control-label">Country Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("country_name", "size" => 30, "class" => "form-control1", "id" => "fieldCountryName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountryCurrency" class="col-sm-2 control-label">Country Currency</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("country_currency", "size" => 30, "class" => "form-control", "id" => "fieldCountryCurrency")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCountryTrade" class="col-sm-2 control-label">Country Trade</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(array("country_trade", array(
                            "Y" => "Yes, allow user to trade this currency",
                            "N" => "No, hide this from currency exchange module"
                        ), "class" => "form-control", "id" => "fieldCountryTrade")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMarkupValue" class="col-sm-2 control-label">Markup Value</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("markup_value", "type" => "number", "class" => "form-control", "id" => "fieldMarkupValue")) ?>
    </div>
</div>

<?php echo $this->tag->hiddenField("country_id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
