<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Country List</h1>
    <p>
        <?php echo $this->tag->linkTo(array("countries/new", "Create countries")) ?>
    </p>
</div>

<?php $this->flash->output(); ?>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "countries/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("country_id", "type" => "number", "class" => "form-control", "id" => "fieldCountryId")) ?>
                    </div>
                </th>
                <th>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("country_name", "size" => 30, "class" => "form-control", "id" => "fieldCountryName")) ?>
                    </div>
                </th>
                <th>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("country_currency", "size" => 30, "class" => "form-control", "id" => "fieldCountryCurrency")) ?>
                    </div>
                </th>
                <th>
                    <div class="col-sm-20">
                        <?php echo $this->tag->selectStatic(array("country_trade", array(
                                            "Y" => "Y",
                                            "N" => "N"
                                        ), "class" => "form-control", "id" => "fieldCountryTrade")) ?>
                    </div>
                </th>
                <th>
                    <div class="col-sm-10">
                        <?php echo $this->tag->textField(array("markup_value", "type" => "number", "class" => "form-control", "id" => "fieldMarkupValue")) ?>
                    </div>
                </th>
                <th colspan="2">
                    <div class="col-sm-offset-2 col-sm-10">
                        <?php echo $this->tag->submitButton(array("Filter", "class" => "btn btn-default")) ?>
                    </div>
                </th>
            </tr>

            <tr>
                <th>Country ID</th>
                <th>Country Name</th>
                <th>Country Currency</th>
                <th><div class="col-sm-20">Country Trade</div></th>
                <th>Markup Value</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $countrie): ?>
            <tr>
                <td><?php echo $countrie->country_id ?></td>
                <td><?php echo $countrie->country_name ?></td>
                <td><?php echo $countrie->country_currency ?></td>
                <td><?php echo $countrie->country_trade ?></td>
                <td><?php echo $countrie->markup_value ?></td>

                <td><?php echo $this->tag->linkTo(array("countries/edit/" . $countrie->country_id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("countries/delete/" . $countrie->country_id, "Delete", "class" => "btn-delete", "onclick"=>"return confirm('Are you sure want to do so?');")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("countries/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("countries/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("countries/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("countries/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>